alglist = {
    "alg_spectralGating":"Spectral Gating",
    "alg_spectralSubtraction":"Spectral Subtraction",
    "alg_wienerFiltering":"Wiener Filtering",
    "alg_addWhiteNoise":"Algorithm to add white noise",
    "alg_addPinkNoise":"Algorithm to add pink noise",
    "alg_addImpulseNoise":"Algorithm to add impulse noise",
    "alg_addGaussianNoise":"Algorithm to add Gaussian noise",
    "alg_addBrownianNoise":"Algorithm to add braownian noise",
    "alg_3stageAlg":"Bandpass+Wavlet Denoising+Smoothing",
    "alg_simulateBT":"Simulate BT recording",
    "alg_scipyNR":"Scipy noise reduction",
    "alg_hilbertVsLowpass":"Envelopes comparison",
    "alg_GaussianSmooth":"Gaussian Smooth",
    "alg_EMD":"Empirical Mode Decomposition",
    "alg_SavitzkyGolayFilter":"Savitzky Golay Filter",
    "alg_MovingAverage":"Moving Average",
    "alg_PeakDetectionSmoothing":"Peak Detection Smoothing",
    "alg_PeakDetectionSmoothing2":"Peak Detection Smoothing",
    "alg_PeakDetectionSmoothing3":"Peak Detection Smoothing",
    "alg_PeakDetectionSmoothing4":"Peak Detection Smoothing",
    "alg_audioChunks":"Audio Chunks",
    "alg_audioChunks2":"Audio Chunks",
    "alg_ExpMovingAvarage":"Exponential Moving Avarage",
    "Alg1":"Noise filter: Band pass 50Hz-2KHz",
    "Alg2":"Spectral Gating",
    "Alg3":"Wiener Filtering",
    "Alg4":"Downsampling",
    "Alg5":"Fast Fourier Transform (FFT)",
    "Alg6":"Mel-Frequency Cepstral Coefficients (MFCC)",
    "Alg7":"Spectrogram",
    "Alg8":"Pitch Shifting",
    "Alg10":"Time-Stretching",
    "Alg11":"Dynamic Range Compression (DRC)",
    "Alg12":"Equalization (EQ)",
    "Alg13":"Envelope Detection",
    "Alg14":"De-reverberation",
    "Alg15":"Pitch Detection (e.g., YIN Algorithm)",
    "Alg16":"High-Pass and Low-Pass Filtering",
    "Alg17":"Feature Scaling",
    "Alg18":"Data Augmentation (for training models)",
    "Alg19":"Voice Activity Detection (VAD)",
    "Alg20":"Root Mean Square Energy (RMSE)",
}