alglist = {
    "Alg1":"Noise filter: Band pass 50Hz-2KHz",
    "Alg2":"Spectral Gating",
    "Alg3":"Wiener Filtering",
    "Alg4":"Downsampling",
    "Alg5":"Fast Fourier Transform (FFT)",
    "Alg6":"Mel-Frequency Cepstral Coefficients (MFCC)",
    "Alg7":"Spectrogram",
    "Alg8":"Pitch Shifting",
    "Alg10":"Time-Stretching",
    "Alg11":"Dynamic Range Compression (DRC)",
    "Alg12":"Equalization (EQ)",
    "Alg13":"Envelope Detection",
    "Alg14":"De-reverberation",
    "Alg15":"De-reverberation",
    "Alg16":"Pitch Detection (e.g., YIN Algorithm)",
    "Alg17":"High-Pass and Low-Pass Filtering",
    "Alg18":"Feature Scaling",
    "Alg19":"Data Augmentation (for training models)",
    "Alg20":"Voice Activity Detection (VAD)",
    "Alg21":"Root Mean Square Energy (RMSE)",
}